### PR TITLE
Ignore IMU-only Controllers in GUI

### LINKED ISSUE #383: Controller input gets stuck in loop spamming PS4 and locking user input.
**Environment**
 - OS/Distribution:   Raspbian Buster 32bit
 - Desktop Environment:  Pixel, X11
 - Hardware:   Rpi4
 - Exact Version or Commit Hash and Installation Method: a11341f built from source.

**Describe the bug**
A couple of times every day Iv'e had this happening, sometimes when I restart chiaki or starting a new game session the in-game is stuck in an input loop, in the game I'm testing with most running on the spot. Whatever is happening is also stopping any further input from the controller reaching the PS4 so I'm not able to break the loop. 
So far I have been 'fixing' it by un-plugging and re-plugging the controller, and shutting down Chiaki and waiting a bit before starting up again.
But now Iv'e been trying to see if I could corner the sequence of events that makes this happen and I think I more or less have it...

**To Reproduce**
1. Start playing a game using a PS4 controller, wired or bluetooth.
2. Keep the Left or Right trigger pressed in while closing the game stream window.
3. Close the Main chiaki window straight after to shut Chiaki down.
4. Wait 3-4 seconds to let the remote wind down, the start the game up again.

It seems if I follow these steps then 75% of the times I can get that loop happening.

I think it seems like I can do this procedure again to unlock the loop. But  it seems a bit lower chance for making that work.

**Expected behavior**
The controller input should never be blocked.

**Log Files**
pi@sensitpi:~/chiaki/chiaki/build $ gui/chiaki
qt5ct: using qt5ct plugin
QEGLPlatformContext: Failed to create context: 3009
[I] Discovery Service detected new host with id 709E29C0519B
[I] Logging to file /home/pi/.local/share/Chiaki/Chiaki/log/chiaki_session_2020-11-22_22-35-26-022022.log
[I] Chiaki Version 1.3.0
[I] Raspberry Pi Decoder initialized
PulseAudioService: pa_context_connect() failed
[I] Controller 1 opened: "PS4 Controller"
[I] Starting session request
[I] Trying to request session from 192.168.1.248:9295
[I] Connected to 192.168.1.248:9295
[I] Sending session request
[I] Session request successful
[I] Starting ctrl
[I] Ctrl connected to 192.168.1.248:9295
[I] Sending ctrl request
[I] Ctrl received http header as response
[I] Ctrl received ctrl request http response
[I] Ctrl connected
[I] Ctrl received Login message: success
[W] Received Ctrl Message with unknown type 0x6
[W] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[W]      0 00 00                                           ..              
[I] Ctrl received valid Session Id: 1606113326IZCEAV6ILCSZWQUZLN77VTTYKVH5I4RJGWZWMNAQXUU4NWOZO4FPMLC5WD6PIFIY
[I] Starting Senkusha
[I] Takion connecting (version 7)
[I] Takion enabled Don't Fragment Bit
[I] Takion sent init
[I] Takion received init ack with remote tag 0x164d97d4, outbound streams: 0x64, inbound streams: 0x64
[I] Takion sent cookie
[I] Takion received cookie ack
[I] Takion connected
[I] Senkusha sending big
[I] Senkusha successfully received bang
[I] Senkusha Ping Test with count 10 starting
[I] Senkusha enabled echo
[I] Senkusha sending Ping 0 of test index 0
[I] Senkusha received Pong, RTT = 0.513 ms
[I] Senkusha sending Ping 1 of test index 0
[I] Senkusha received Pong, RTT = 0.570 ms
[I] Senkusha sending Ping 2 of test index 0
[I] Senkusha received Pong, RTT = 0.495 ms
[I] Senkusha sending Ping 3 of test index 0
[I] Senkusha received Pong, RTT = 0.488 ms
[I] Senkusha sending Ping 4 of test index 0
[I] Senkusha received Pong, RTT = 0.496 ms
[I] Senkusha sending Ping 5 of test index 0
[I] Senkusha received Pong, RTT = 0.543 ms
[I] Senkusha sending Ping 6 of test index 0
[I] Senkusha received Pong, RTT = 0.524 ms
[I] Senkusha sending Ping 7 of test index 0
[I] Senkusha received Pong, RTT = 0.438 ms
[I] Senkusha sending Ping 8 of test index 0
[I] Senkusha received Pong, RTT = 0.468 ms
[I] Senkusha sending Ping 9 of test index 0
[I] Senkusha received Pong, RTT = 0.661 ms
[I] Senkusha disabled echo
[I] Senkusha determined average RTT = 0.519 ms
[I] Senkusha starting MTU in test with min 576, max 1454, retries 3, timeout 5 ms
[I] Senkusha MTU request 1454 (min 576, max 1454), id 1, attempt 0
[I] Senkusha MTU 1454 success
[I] Senkusha determined inbound MTU 1454
[I] Senkusha starting MTU out test with min 576, max 1454, retries 3, timeout 5 ms
[I] Senkusha sent initial client MTU command
[I] Senkusha received expected Client MTU Command
[I] Senkusha MTU 1454 out ping attempt 0
[I] Senkusha MTU ping 1454 success
[I] Senkusha determined outbound MTU 1454
[I] Senkusha sending final Client MTU Command
[I] Senkusha is disconnecting
[I] Senkusha closed takion
[I] Senkusha completed successfully
[I] Takion connecting (version 9)
[I] Takion sent init
[I] Takion received init ack with remote tag 0x4b8853, outbound streams: 0x64, inbound streams: 0x64
[I] Takion sent cookie
[I] Takion received cookie ack
[I] Takion connected
[I] StreamConnection sending big
[I] BANG received
[I] StreamConnection successfully received bang
[I] Crypt has become available. Re-checking MACs of 0 packets
[D] StreamConnection received audio header:
[D] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[D]      0 02 10 00 00 bb 80 00 00 01 e0 00 00 00 01       ..............  
[I] Audio Header:
[I]   channels = 2
[I]   bits = 16
[I]   rate = 48000
[I]   frame size = 480
[I]   unknown = 1
[I] ChiakiOpusDecoder initialized
[I] Audio Device default opened with 2 channels @ 48000 Hz, buffer size 19200
[I] Video Profiles:
[I]   0: 1280x720
[I] StreamConnection successfully received streaminfo
[I] Switched to profile 0, resolution: 1280x720
[I] StreamConnection is disconnecting
[I] StreamConnection sending Disconnect
[I] StreamConnection was requested to stop
[I] StreamConnection closed takion
[I] StreamConnection completed successfully
[I] Ctrl requested to stop
[I] Ctrl stopped
[I] Session has quit

### LINKED ISSUE #384: Occasionally Chiaki doesn't take controller input at all
**Environment**
 - OS/Distribution: Raspbian Buster 32bit
 - Desktop Environment:  Pixel, X11
 - Hardware: RPi4
 - Exact Version or Commit Hash and Installation Method: a11341f

**Describe the bug**
Now and then when I'm starting up a new session the DS4 (also happens with my xbox controller) Chiaki won't take any controller input at all. Its completely dead.
I then have to un-plug and re-plug the usb controller a few times to get it working again. Often I can do that without having to restart the game session. 

**To Reproduce**
1. Sorry I don't know how to trigger this one.

**Expected behavior**
Controllers should always work.
This is especially bad when it happens over bluetooth mode as then I'll have to actuall turn off bluetooth on the Pi get the USB cable and re-plug a few times and the go back to bluetooth.

**Log Files**
pi@sensitpi:~/chiaki/chiaki/build $ gui/chiaki
qt5ct: using qt5ct plugin
QEGLPlatformContext: Failed to create context: 3009
[I] Discovery Service detected new host with id 709E29C0519B
[I] Logging to file /home/pi/.local/share/Chiaki/Chiaki/log/chiaki_session_2020-11-22_22-25-40-496496.log
[I] Chiaki Version 1.3.0
[I] Raspberry Pi Decoder initialized
PulseAudioService: pa_context_connect() failed
[I] Starting session request
[I] Trying to request session from 192.168.1.248:9295
[I] Connected to 192.168.1.248:9295
[I] Sending session request
[I] Session request successful
[I] Starting ctrl
[I] Ctrl connected to 192.168.1.248:9295
[I] Sending ctrl request
[I] Ctrl received http header as response
[I] Ctrl received ctrl request http response
[I] Ctrl connected
[I] Ctrl received Login message: success
[W] Received Ctrl Message with unknown type 0x6
[W] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[W]      0 00 00                                           ..              
[I] Ctrl received valid Session Id: 1606112741PNHV4J3MNU4WPA3ABIFGHHDEE22CE6TK2FIOGCWTEYASFHM4H222ZGZ4RZKYPNY7
[I] Starting Senkusha
[I] Takion connecting (version 7)
[I] Takion enabled Don't Fragment Bit
[I] Takion sent init
[I] Takion received init ack with remote tag 0x144f9281, outbound streams: 0x64, inbound streams: 0x64
[I] Takion sent cookie
[I] Takion received cookie ack
[I] Takion connected
[I] Senkusha sending big
[I] Senkusha successfully received bang
[I] Senkusha Ping Test with count 10 starting
[I] Senkusha enabled echo
[I] Senkusha sending Ping 0 of test index 0
[I] Senkusha received Pong, RTT = 0.541 ms
[I] Senkusha sending Ping 1 of test index 0
[I] Senkusha received Pong, RTT = 0.524 ms
[I] Senkusha sending Ping 2 of test index 0
[I] Senkusha received Pong, RTT = 0.507 ms
[I] Senkusha sending Ping 3 of test index 0
[I] Senkusha received Pong, RTT = 0.518 ms
[I] Senkusha sending Ping 4 of test index 0
[I] Senkusha received Pong, RTT = 0.441 ms
[I] Senkusha sending Ping 5 of test index 0
[I] Senkusha received Pong, RTT = 0.474 ms
[I] Senkusha sending Ping 6 of test index 0
[I] Senkusha received Pong, RTT = 0.558 ms
[I] Senkusha sending Ping 7 of test index 0
[I] Senkusha received Pong, RTT = 0.515 ms
[I] Senkusha sending Ping 8 of test index 0
[I] Senkusha received Pong, RTT = 0.438 ms
[I] Senkusha sending Ping 9 of test index 0
[I] Senkusha received Pong, RTT = 0.520 ms
[I] Senkusha disabled echo
[I] Senkusha determined average RTT = 0.503 ms
[I] Senkusha starting MTU in test with min 576, max 1454, retries 3, timeout 5 ms
[I] Senkusha MTU request 1454 (min 576, max 1454), id 1, attempt 0
[I] Senkusha MTU 1454 success
[I] Senkusha determined inbound MTU 1454
[I] Senkusha starting MTU out test with min 576, max 1454, retries 3, timeout 5 ms
[I] Senkusha sent initial client MTU command
[I] Senkusha received expected Client MTU Command
[I] Senkusha MTU 1454 out ping attempt 0
[I] Senkusha MTU ping 1454 success
[I] Senkusha determined outbound MTU 1454
[I] Senkusha sending final Client MTU Command
[I] Senkusha is disconnecting
[I] Senkusha closed takion
[I] Senkusha completed successfully
[I] Takion connecting (version 9)
[I] Takion sent init
[I] Takion received init ack with remote tag 0x30c1c81b, outbound streams: 0x64, inbound streams: 0x64
[I] Takion sent cookie
[I] Takion received cookie ack
[I] Takion connected
[I] StreamConnection sending big
[I] BANG received
[I] StreamConnection successfully received bang
[I] Crypt has become available. Re-checking MACs of 0 packets
[D] StreamConnection received audio header:
[D] offset 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
[D]      0 02 10 00 00 bb 80 00 00 01 e0 00 00 00 01       ..............  
[I] Audio Header:
[I]   channels = 2
[I]   bits = 16
[I]   rate = 48000
[I]   frame size = 480
[I]   unknown = 1
[I] ChiakiOpusDecoder initialized
[I] Audio Device default opened with 2 channels @ 48000 Hz, buffer size 19200
[I] Video Profiles:
[I]   0: 1280x720
[I] StreamConnection successfully received streaminfo
[I] Switched to profile 0, resolution: 1280x720
[I] Ctrl received Heartbeat, sending reply
[I] Ctrl received Heartbeat, sending reply
[I] Ctrl received Heartbeat, sending reply
[I] Ctrl received Heartbeat, sending reply
[I] Ctrl received Heartbeat, sending reply
[I] StreamConnection is disconnecting
[I] StreamConnection sending Disconnect
[I] StreamConnection was requested to stop
[I] StreamConnection closed takion
[I] StreamConnection completed successfully
[I] Ctrl requested to stop
[I] Ctrl stopped
[I] Session has quit

**Additional context**
I wonder if this is connected to the other bug I just posted about?

### PR DESCRIPTION
**Pull request by Fredrum**
Hi Florian!

- I discovered that the DS4 actually needs two SDL joysticks, one for IMU/Motion and one for standard inputs.

- It was confusing having 2x Chiaki Controllers, 2x SDL Controllers and 2x SDL_Joysticks for the DS4 so for this pr I have changed the 'controller' names to 'chiaki_controller' and 'sdl_controller' to be able to immediately see which is which.

- I'm trying to channel everything through the Events now. Even the initial startup controller setup.

- SDL keeps and uses a no-reuse and continually increasing 'instance_id' for joysticks. I have been using that whenever possible instead of SDL_NumJoysticks(). I'm using that fact to avoid having to re-order lists when controller un-plugs and re-plugs. I just keep going with the higher numbers. This saves me some complexity.

- There's still something that causes a segfault every 3rd or 4th time I pull out the controller usb cord while playing. I'm guessing some pointer thing I'm doing wrong. Let me know if you spot it but I'll keep trying to find it too so that can be solid.

- I don't need to 'push' right for you to see this work? 
There should only be 1 commit with this pr. Four files.

-----------------------------------------------------------------------------------------------------------------------
Update,

so apart from being able to filter off the Motion control Events from the secondary DS4 controller I also wanted to get to a place where I didn't have the instability I had before. See https://github.com/thestr4ng3r/chiaki/issues/384  and  https://github.com/thestr4ng3r/chiaki/issues/383

I don't get those problems now with this system.
I believe the problem was that since it wasn't handling the two sub-devices random things happened when one unplugged a controller and plugged back in. Sometimes it got stuck in that motion sensor spamming mode and sometimes I couldn't reconnect with a controller at all.

SO this system was a result of me just reading about how people used SDL for controller handling. For example to handle all through the Events.

But basically the main things I wanted to achieve was to get rid of the buggy behavior described in those two 'issues' tickets.  And then when I realized about the two SDL controllers for the DS4 it made sense to do a filter for that.

Fix #383
Fix #384

### CODE REVIEW

**Comment by Fredrum** [comment]
Ok I hope and think, fingers crossed, that this one should be good?
Just let me know if it still isn't?

Iv'e been watching about re-basing and since they seemed to say that it was dangerous to do against a remote directly I have done it via a local master that I pulled from your master just now.

Then rebased my feature(rpi01) and my master against each other.

I did get some strange merge conflict that I wasn't able to get rid of without a push --force.
That was in  settingsdialog.cpp and seemed to be just a single whitespace thing. I even tried copying and pasting the entirety of your file since I hadn't worked in it.

**Comment by thestr4ng3r** [comment]
Nope, still messed up. You can easily check this yourself. For example here on the pr on github, it should only show the commits you added yourself and the diff should also only contain these changes.


> Iv'e been watching about re-basing and since they seemed to say that it was dangerous to do against a remote directly I have done it via a local master that I pulled from your master just now.

I wouldn't consider rebasing against a remote branch to be dangerous, there isn't really any difference in whether the branch to rebase on is remote or not.
Assuming you have `git@github.com:thestr4ng3r/chiaki` saved as for example `upstream` and `git@github.com:Fredrum/chiaki` as `origin` and you are currently on your branch that has your changes, you can do `git fetch upstream`, then `git rebase -i upstream/master` and it will show you a list of commits that it would put on top of `upstream/master`. Delete all the lines that are not exactly your commits, save and quit and you will have a nice history. After this, force push is naturally necessary because the history is different.

**Comment by Fredrum** [comment]
Ok, now the four files I have changed are the same ones I see under the PR 'Files Changed' and it looks like the stuff Iv'e done too.

I think I got rid of the segfault thing too.

It's quite a radical change from how it was before so I'm hoping I haven't broken anything that I couldn't test. Like on the Android side or anything like that?

**Comment by thestr4ng3r** [comment]
Yes, now the history is perfect.
Could you please edit the pr description with a short and concise explanation of what exactly you are trying to achieve? All I can tell is that you would like to filter out the imu controller and I think this could be done by just adding approximately three lines in `UpdateGamepads()` so I'm not sure what all the changes are for.

**Comment by Fredrum** [comment]
Just added another bit to this OP.

**Comment by thestr4ng3r** [comment]
Thanks, I see now. So what I would do before considering all these changes would be to make a clean new branch from the current chiaki master and only apply the filtering exactly before this line: https://github.com/thestr4ng3r/chiaki/blob/777c3a649a7bfb0108bb5610d381c8679e2b75be/gui/src/controllermanager.cpp#L59 and check if that can already fix all of your issues.
The filter should however **not** use `SDL_JoystickName()` as that can be abitrary info. `SDL_JoystickGetGUID()` et al. seem fitting here.

**Comment by Fredrum** [comment]
Just tried checking the GUIDs but unfortunately they are the same for both sub-controllers,

```
GUID Name:  030000004c050000c405000011810000
[I] Connected: Sony Computer Entertainment Wireless Controller
GUID Name:  030000004c050000c405000011810000
[I] Connected: Sony Computer Entertainment Wireless Controller Motion Sensors
```

But I see that for the DS4 it returns '0' (zero) from,
`int SDL_JoystickNumButtons(SDL_Joystick* joystick)`

I'm not sure if that's 100% safe to use as an identifier, but do you feel that would be better?

**Comment by thestr4ng3r** [comment]
I would combine checking the guid and NumButtons and only if both criteria match, ignore the controller.
Did you also have the chance to check how the guids look for controllers that are not the DS4, or another DS4 of the same generation? So we know that our check both doesn't cover more controllers than we want and it is not specific to only the controller that you own.
Also, maybe `SDL_JoystickGetDeviceGUID()` is interesting too.

**Comment by Fredrum** [comment]
HI so the GUID's are not telling me anything about if the controller has a separate SDL controller motion component. Both my ds4 pads are the same model and have the same guid. I have two xbox one controllers that are have different guid from the ds4's but the same as each other.
That command SDL_JoystickGetDeviceGUID() gave me the same guid as the other command.
There's a long community list that is kept up to date here where you can see loads of guid's and what they are,    https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

So now I'm only checking against '0 buttons'.
I think this is probably something that can be added to if people are having trouble with some other controller that is not following the same pattern.

And your suggestion seems to work fine! :) Much less code change. Although I learned quite a bit about SDL controllers.

And because this  was now such a small edit Iv'e thrown in two other things that I wanted to also do after the controller fix.

1. Add a double click action for the stream window. I'm wanting to be able to use only a gamepad, no KB+M, to start a game session on the Pi. And that bit was missing. Now I can use the DS4s touchpad to double click to toggle full screen. Similar to VLC or Netflix.

2. The Audio menu had ended up after the 'About Chiaki' menu and it irked me. So I just moved that up one step.

**Comment by thestr4ng3r** [comment]
Yes, checking against a set of guids sounds good to me. Please move the other changes to separate prs. If possible, individual pull requests should be as small as possible.

**Comment by Fredrum** [comment]
Just re-did this one with just the SDL bits, including a guid lookup.

**Comment by Fredrum** [comment]
With the other two PRs, do you need them separated out?
So ontop of your Master? Or can they be gradually appending each other?

File: gui/src/controllermanager.cpp [hunk 1]
```diff
@@ -56,7 +57,15 @@ void ControllerManager::UpdateAvailableControllers()
 	{
 		if(!SDL_IsGameController(i))
 			continue;
-		current_controllers.insert(SDL_JoystickGetDeviceInstanceID(i));
+
+		// We'll try to identify pads with Motion Control
+		SDL_JoystickGUID guid = SDL_JoystickGetGUID(SDL_JoystickOpen(i));
+		char guid_str[256];
+		SDL_JoystickGetGUIDString(guid, guid_str, 256);
```
Comment (thestr4ng3r) [inline gui/src/controllermanager.cpp:64]: This is safer:
```suggestion
		SDL_JoystickGetGUIDString(guid, guid_str, sizeof(guid_str));
```

File: gui/include/motioncontrollers.h [hunk 2]
```diff
@@ -0,0 +1,68 @@
+// SPDX-License-Identifier: LicenseRef-GPL-3.0-or-later-OpenSSL
+
+#ifndef CHIAKI_MOTIONCONTROLLERS_H
+#define CHIAKI_MOTIONCONTROLLERS_H
+
+// Taken from https://github.com/gabomdq/SDL_GameControllerDB
+// The assumption is that the PS3(sixaxis), DS3 and DS4 do have
+// a motion control component.
+
+QList<QString> chiaki_motion_controller_guid_list({
```
Comment (thestr4ng3r) [inline gui/include/motioncontrollers.h:10]: Make this `static QSet<QString> ...` instead of QList, then you will need to use `.contains()` instead of `.indexOf()`. Also no need for an extra file, you can just drop it in controllermanager.cpp

File: gui/src/controllermanager.cpp [hunk 3]
```diff
@@ -56,7 +57,15 @@ void ControllerManager::UpdateAvailableControllers()
...
+
+		int nButtons = SDL_JoystickNumButtons(SDL_JoystickOpen(i));
+		if(!(nButtons == 0 && chiaki_motion_controller_guid_list.indexOf(guid_str) > -1))
+			current_controllers.insert(SDL_JoystickGetDeviceInstanceID(i));
```
Comment (thestr4ng3r) [inline gui/src/controllermanager.cpp:68]: Joysticks opened with `SDL_JoystickOpen()` must be closed and early return should be used.
So better to restructure this to something like this (untested, but I think you get the idea):

```c++
		if(chiaki_motion_controller_guids.contains(guid_str))
		{
			SDL_Joystick *joy = SDL_JoystickOpen(i);
			if(joy)
			{
				bool no_buttons = SDL_JoystickNumButtons(joy) == 0;
				SDL_JoystickClose(joy);
				if(no_buttons)
					continue;
			}
		}

		current_controllers.insert(SDL_JoystickGetDeviceInstanceID(i));
```

**Review by thestr4ng3r — CHANGES_REQUESTED** [review]
Adjust according to these comments, then it should be good.

**Comment by thestr4ng3r** [comment]
> With the other two PRs, do you need them separated out?
> So each ontop of your Master? Or can they be gradually appending each other?

PRs should always be based on the target branch they should be merged into, which in this case is master here. Except in cases where the contents of the PR depend on something else but that is not the case here.
So yes, each independently on top of master.

**Comment by Fredrum** [comment]
Ok that should be it now!?

**Review by thestr4ng3r — APPROVED** [review]
Perfect, thanks!
