### PR TITLE
Use ChiakiKeyState to 32bit fix key state overflow (Fix #172)

### LINKED ISSUE #172: Getting stuck after about 2hr of streaming
I'm using linux mint.
Chiaki gets stuck in about 1 - 2 and half hours of streaming. The screen doesn't go black its just stuck in the last frame without any sound. I checked the system monitor and Chiaki was still downloading data. If I just relaunch Chiaki after a few seconds it's started working again.
If u can fix that I would really appreciate it.

### PR DESCRIPTION
**Pull request by svnscha**
Fix #172

### CODE REVIEW

File: lib/include/chiaki/takion.h [hunk 1]
```diff
@@ -55,7 +53,7 @@ static inline uint8_t chiaki_takion_av_packet_audio_unit_size(ChiakiTakionAVPack
 static inline uint8_t chiaki_takion_av_packet_audio_source_units_count(ChiakiTakionAVPacket *packet)	{ return packet->units_in_frame_fec & 0xf; }
 static inline uint8_t chiaki_takion_av_packet_audio_fec_units_count(ChiakiTakionAVPacket *packet)		{ return (packet->units_in_frame_fec >> 4) & 0xf; }
 
-typedef ChiakiErrorCode (*ChiakiTakionAVPacketParse)(ChiakiTakionAVPacket *packet, uint8_t *buf, size_t buf_size);
+typedef ChiakiErrorCode (*ChiakiTakionAVPacketParse)(ChiakiTakionAVPacket *packet, ChiakiKeyState* keystate, uint8_t *buf, size_t buf_size);
```
Comment (thestr4ng3r) [inline lib/include/chiaki/takion.h:56]:
```suggestion
typedef ChiakiErrorCode (*ChiakiTakionAVPacketParse)(ChiakiTakionAVPacket *packet, ChiakiKeyState *key_state, uint8_t *buf, size_t buf_size);
```

File: lib/include/chiaki/takion.h [hunk 2]
```diff
@@ -220,15 +220,15 @@ CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_send_feedback_history(ChiakiTakion *
...
+CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_v9_av_packet_parse(ChiakiTakionAVPacket *packet, ChiakiKeyState *keystate, uint8_t *buf, size_t buf_size);
 
 #define CHIAKI_TAKION_V7_AV_HEADER_SIZE_BASE					0x12
 #define CHIAKI_TAKION_V7_AV_HEADER_SIZE_VIDEO_ADD				0x3
 #define CHIAKI_TAKION_V7_AV_HEADER_SIZE_NALU_INFO_STRUCTS_ADD	0x3
 
 CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_v7_av_packet_format_header(uint8_t *buf, size_t buf_size, size_t *header_size_out, ChiakiTakionAVPacket *packet);
 
-CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_v7_av_packet_parse(ChiakiTakionAVPacket *packet, uint8_t *buf, size_t buf_size);
+CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_v7_av_packet_parse(ChiakiTakionAVPacket *packet, ChiakiKeyState* keystate, uint8_t *buf, size_t buf_size);
```
Comment (thestr4ng3r) [inline lib/include/chiaki/takion.h:231]:
```suggestion
CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_v7_av_packet_parse(ChiakiTakionAVPacket *packet, ChiakiKeyState *keystate, uint8_t *buf, size_t buf_size);
```

File: lib/src/takion.c [hunk 3]
```diff
@@ -338,7 +339,7 @@ CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_send_raw(ChiakiTakion *takion, const
 }
 
 
-static ChiakiErrorCode chiaki_takion_packet_mac(ChiakiGKCrypt *crypt, uint8_t *buf, size_t buf_size, uint8_t *mac_out, uint8_t *mac_old_out, ChiakiTakionPacketKeyPos *key_pos_out)
+static ChiakiErrorCode chiaki_takion_packet_mac(ChiakiGKCrypt *crypt, ChiakiKeyState* keystate, uint8_t *buf, size_t buf_size, uint8_t *mac_out, uint8_t *mac_old_out, uint64_t *key_pos_out)
```
Comment (thestr4ng3r) [inline lib/src/takion.c:342]:
```suggestion
static ChiakiErrorCode chiaki_takion_packet_mac(ChiakiGKCrypt *crypt, ChiakiKeyState *key_state, uint8_t *buf, size_t buf_size, uint8_t *mac_out, uint8_t *mac_old_out, uint64_t *key_pos_out)
```

File: lib/src/takion.c [hunk 4]
```diff
@@ -349,22 +350,24 @@ static ChiakiErrorCode chiaki_takion_packet_mac(ChiakiGKCrypt *crypt, uint8_t *b
...
+	if(buf_size < mac_offset + CHIAKI_GKCRYPT_GMAC_SIZE || buf_size < key_pos_offset + sizeof(uint32_t))
 		return CHIAKI_ERR_BUF_TOO_SMALL;
 
 	if(mac_old_out)
 		memcpy(mac_old_out, buf + mac_offset, CHIAKI_GKCRYPT_GMAC_SIZE);
 
 	memset(buf + mac_offset, 0, CHIAKI_GKCRYPT_GMAC_SIZE);
 
-	ChiakiTakionPacketKeyPos key_pos = ntohl(*((ChiakiTakionPacketKeyPos *)(buf + key_pos_offset)));
+	uint32_t key_pos_lo = ntohl(*((uint32_t *)(buf + key_pos_offset)));
```
Comment (thestr4ng3r) [inline lib/src/takion.c:361]:
```suggestion
	uint32_t key_pos_lo = ntohl(*((chiaki_unaligned_uint32_t *)(buf + key_pos_offset)));
```
(was wrong before this pr too)

File: lib/src/takion.c [hunk 5]
```diff
@@ -349,22 +350,24 @@ static ChiakiErrorCode chiaki_takion_packet_mac(ChiakiGKCrypt *crypt, uint8_t *b
...
 
 	if(crypt)
 	{
 		if(base_type == TAKION_PACKET_TYPE_CONTROL)
-			memset(buf + key_pos_offset, 0, sizeof(ChiakiTakionPacketKeyPos));
+			memset(buf + key_pos_offset, 0, sizeof(uint32_t));
+
 		chiaki_gkcrypt_gmac(crypt, key_pos, buf, buf_size, buf + mac_offset);
-		*((ChiakiTakionPacketKeyPos *)(buf + key_pos_offset)) = htonl(key_pos);
+		*((uint32_t *)(buf + key_pos_offset)) = htonl(key_pos);
```
Comment (thestr4ng3r) [inline lib/src/takion.c:370]:
```suggestion
		*((chiaki_unaligned_uint32_t *)(buf + key_pos_offset)) = htonl(key_pos);
```

File: lib/src/takion.c [hunk 6]
```diff
@@ -381,7 +384,7 @@ CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_send(ChiakiTakion *takion, uint8_t *
 	if(err != CHIAKI_ERR_SUCCESS)
 		return err;
 	uint8_t mac[CHIAKI_GKCRYPT_GMAC_SIZE];
-	err = chiaki_takion_packet_mac(takion->gkcrypt_local, buf, buf_size, mac, NULL, NULL);
+	err = chiaki_takion_packet_mac(takion->gkcrypt_local, &takion->keystate, buf, buf_size, mac, NULL, NULL);
```
Comment (thestr4ng3r) [inline lib/src/takion.c:387]: `&takion->keystate` is remote here, but send is local

File: lib/src/takion.c [hunk 7]
```diff
@@ -1202,7 +1205,7 @@ static void takion_handle_packet_av(ChiakiTakion *takion, uint8_t base_type, uin
 	}
 }
 
-CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_v9_av_packet_parse(ChiakiTakionAVPacket *packet, uint8_t *buf, size_t buf_size)
+CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_v9_av_packet_parse(ChiakiTakionAVPacket *packet, ChiakiKeyState* keystate, uint8_t *buf, size_t buf_size)
```
Comment (thestr4ng3r) [inline lib/src/takion.c:1208]:
```suggestion
CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_v9_av_packet_parse(ChiakiTakionAVPacket *packet, ChiakiKeyState *keystate, uint8_t *buf, size_t buf_size)
```

File: lib/src/takion.c [hunk 8]
```diff
@@ -1242,8 +1245,8 @@ CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_v9_av_packet_parse(ChiakiTakionAVPac
 	}
 
 	packet->codec = av[8];
-
 	packet->key_pos = ntohl(*((chiaki_unaligned_uint32_t *)(av + 0xd)));
```
Comment (thestr4ng3r) [inline lib/src/takion.c:1248]: Better use a local variable for the intermediate key_pos.

File: lib/src/takion.c [hunk 9]
```diff
@@ -1242,8 +1245,8 @@ CHIAKI_EXPORT ChiakiErrorCode chiaki_takion_v9_av_packet_parse(ChiakiTakionAVPac
...
+   packet->key_pos = chiaki_key_state_request_pos(keystate, packet->key_pos);
```
Comment (thestr4ng3r) [inline lib/src/takion.c:1249]:
```suggestion
	packet->key_pos = chiaki_key_state_request_pos(keystate, packet->key_pos);
```

**Review by thestr4ng3r — COMMENTED** [review]
* `ChiakiGKCrypt.key_buf_key_pos_min` and `last_key_pos` also have to be `uint64_t`
* `keystate` -> `key_state`
* unit tests are broken

Since this is a huge pain to test irl I think we should have unit tests for the following things:
* in `test/gkcrypt.c` in the functions `test_key_stream`, `test_endecrypt` and `test_gmac`, add additional cases for key_pos >=`1<<32`, ideally even >=`2<<32`. This can happen in the already existing functions with the same keys and stuff. Mostly to ensure consistency between 64bit and 32bit platforms.
* In `test/takion.c`, test for the actual packet handling somehow. Can't say yet what the best way for this will be.

But the additional tests aren't requirements to merge this.
